version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.1
  
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "yarn-lock.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "yarn-lock.json" }}
      - run: yarn test
